#!/bin/bash

# Update package lists and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Modify the default server block configuration
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Ensure Nginx is listening on port 80 (default port)
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Restart Nginx - without using systemctl
sudo kill -s HUP $(cat /var/run/nginx.pid)

